### ISSUE TITLE
Deprecated GITHUB_PAT 

### ISSUE THREAD

**Issue by lolow** [r-lib/gh#106]
I received these emails from github, telling me that  `access_token` query parameter is deprecated. 

See below,
```
On February 5th, 2020 at 10:25 (UTC) your personal access token (R:GITHUB_PAT) using libcurl/7.66.0 r-curl/4.3 httr/1.4.1 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/1272xxxx/releases/assets/158xxxx

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

I am using the `piggyback` package but I think this might be more related to the `gh` package. How should I proceed to use the ` Authorization HTTP header` instead? The documentation only relates to the access token.

**Comment by gaborcsardi** [comment]
AFAICT gh only sends the token as a header, and piggyback sets it explicitly as as query parameter, e.g. here:
https://github.com/ropensci/piggyback/blob/2e741b814708ed463c6b693e5f04617e9418df76/R/pb_download.R#L144

So this seems like a piggyback issue to me.

**Comment by lolow** [comment]
thanks a lot, Il forward the issue.
