### ISSUE TITLE
Token: check for env var first, then the keyring

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gh#110]
That's a better user experience, because the keyring check might bring up some dialogs, even if the token is in an env var.

**Comment by jennybc** [comment]
How do you see this in light of #120 and the capabilities of credentials?

Would you want to drop keyring, in favour of the git credential store, which credentials uses? Or should there be some way to indicate you want to manage the PAT with keyring instead of consulting the git credential store?

**Comment by jennybc** [comment]
I have a better grip on things now and I believe this is a simple fix, which I'll do as part of #123.
