### ISSUE TITLE
Upload a image feature

### ISSUE THREAD

**Issue by CrisHarry** [r-lib/gh#112]
I have a question is there any way that I can upload a file (image) using gitAPI. Please help me if you have any ideas or workarounds. I appreciate it.

**Comment by gaborcsardi** [comment]
I suspect that this is possible, yeah.

**Comment by gaborcsardi** [comment]
@CrisHarry To which API endpoint in particular?

**Comment by hadley** [comment]
I thought the most likely end point would be uploading a profile picture, but I can't find that in the API: https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#update-the-authenticated-user. And since it's been >2 years without further discussion, I'm going to close this issue.
