### ISSUE TITLE
Adding some helper functions?

### ISSUE THREAD

**Issue by pat-s** [r-lib/gh#131]
In {travis} and {tic} we have a bunch of helper funs to undertake some common tasks (permission handling, getting owners, writing secrets and SSH keys) on GitHub:

- https://github.com/ropenscilabs/travis/blob/f2dd9a3640b0cd8266b0a813c8eaf6bf3775c83d/R/github-key.R
- https://github.com/ropenscilabs/travis/blob/f2dd9a3640b0cd8266b0a813c8eaf6bf3775c83d/R/github-auth.R

Updating them in two places (and possible more places) is tedious so we were wondering whether it would make sense to add them to {gh}?
Under the hood they make use of {usethis}, {gh}, {openssl} and {sodium}. {usethis} could be easily replaced though.

Of course importing {openssl} and {sodium} would be heavy for {gh} so I'd suggest to put them into SUGGESTS and make them optional?

**Comment by gaborcsardi** [comment]
I would rather put (most of?) these in a FAQ vignette, to avoid new dependencies.

**Comment by jennybc** [comment]
I also like the idea of an article that showcases usage. As a general idea and as a substitute for gh gaining higher-level functions, which would definitely become a slippery slope.

**Comment by jennybc** [comment]
I think this theme that showing real usage often drags in other packages is legitimate (and I feel it too). Because you often will need, e.g., data wrangling or other pre-/post-processing when using gh to accomplish specific objectives.

**Comment by hadley** [comment]
I think we're now more committed to not growing the scope of gh in this way, so I'm going to close.
