### ISSUE TITLE
Weird behavior with .limit on actions api endpoints

### ISSUE THREAD

**Issue by rundel** [r-lib/gh#135]
I've run into some weird behavior when trying to set a limit for results coming from the actions api (it may affect other areas - I haven't tested beyond these endpoints). Seems to be a problem with the paging, but I haven't dug into the underlying code.

```
ok = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh"
)

error = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh",
  .limit = 1
)

badly_formed = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh",
  .limit = 10
)
```

**Comment by gaborcsardi** [comment]
So, #136 fixes the `badly_formed` query, but the `error` one is still an error, is that expected?

**Comment by rundel** [comment]
I don't think that is expected - I clearly didn't test against my own test cases.

**Comment by rundel** [comment]
I think the issue is around comparing `length(res)` to `.limit` since the former is not correct for the "named result" case

**Comment by gaborcsardi** [comment]
Yeah, we should probably measure the length differently in the "named result" case.

**Comment by gaborcsardi** [comment]
OTOH, this is in some sense a different issue from the one you fixed.

**Comment by rundel** [comment]
I think the while loop bit can be fixed by counting pages and then checking that `pages * per_page < .limit`, the harder bit is with the subsetting to obtain the `.limit` length in the final conditional because it is not obvious which of the elements contains the results.

**Comment by gaborcsardi** [comment]
> I think the while loop bit can be fixed by counting pages and then checking that pages * per_page < .limit

Yeah, although th API is not guaranteed to give you `per_page` results. Still better than the current behavior I guess.

> not obvious which of the elements contains the results.

Yeah.

**Comment by gaborcsardi** [comment]
@rundel Can we use `total_count` to inform us about the response type? 

Btw. there is an API spec now, which will make our lives easier, even though it is massive: https://github.com/github/rest-api-description/tree/main/descriptions/api.github.com

**Comment by rundel** [comment]
I wasn't sure if `total_count` was consistent across the api - I feel like there were a few cases that used something else, but I may be confusing that the with result unnamed array.

**Comment by rundel** [comment]
The API spec looks like it might be useful - it seems like within the schema definition they distinguish between "object" results vs "array" results.

There are still some other edge cases, the `/user` endpoint has the following schema:
```
"schema": {
  "oneOf": [
    {
      "$ref": "#/components/schemas/private-user"
    },
    {
      "$ref": "#/components/schemas/public-user"
    }
  ]
}
```

**Comment by gaborcsardi** [comment]
https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/dereferenced/api.github.com.deref.yaml has the complete schema, with the refs expanded. In any case that specific example is an object, not an array.

**Comment by gaborcsardi** [comment]
I think we can go with `total_count`. I am working on a fix.

**Comment by gaborcsardi** [comment]
@rundel Does this look reasonable to you? https://github.com/r-lib/gh/pull/141 Thanks!
