### ISSUE TITLE
Basic token validation

### ISSUE THREAD

**Issue by jeroen** [r-lib/gh#143]
Somewhat related to https://github.com/r-lib/gh/issues/133 but simpler:

I have been debugging a `GitHub API error (422): 422 Unprocessable Entity` for a long time. The problem was that the GHA UI where you have to save secrets had appended a `\n` at the end of the secret. Apparently this makes the token invalid.

It would make sense to have `gh` do some basic validation on the token format, before calling to the API. Something as simple as `grepl('[a-f0-9]{40}$',  token)` could work.

As a side node, gh-apps tokens are prefixed with `v1.` and then the usual hash.

**Comment by gaborcsardi** [comment]
Right. It would be good not to make too many assumptions about what can be in a token, but obviously `\n` should not be in there.

How about removing newlines with a warning?

**Comment by jeroen** [comment]
I think we can be a bit more strict to catch obviously wrong problems. For example if the token has a space or is obviously too short. I think errori'ng would be better than trying to silently fix the thing, because the same token my be used elsewhere.

**Comment by gaborcsardi** [comment]
A warning is not silent, though. And in your secret case, if the UI always puts in the `\n`, and gh errors on this, then how can you even use gh?

**Comment by jeroen** [comment]
Well it was eventually a copy-paste error on my end, if you copy the PAT into the webpage, it automatically adds an eol. So you just have to be careful to remove that, before pressing save.

Yes a warning would do as well, though this is easy to go unnoticed in a CI job.

**Comment by gaborcsardi** [comment]
> Yes a warning would do as well, though this is easy to go unnoticed in a CI job.

Right, but if the token is really needed, the CI job will sooner or later fail.

I am just a bit worried about making it an error, because if GH comes up with another token format that is invalid for us, that will break everything.

**Comment by jeroen** [comment]
Yes that is right. Ok so maybe a warning if the token contains any sort of whitespace? Or is that also a risk?

**Comment by gaborcsardi** [comment]
No, that's fine I think.
