### ISSUE TITLE
Update PAT validation

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#148]
https://github.blog/changelog/2021-03-04-authentication-token-format-updates/

PATs are included in in "each of these token types" here:

> For each of these token types we are making the following changes:
> 
>   * The character set is changing from [a-f0-9] to [A-Za-z0-9_]
>   * The format is changing to include a prefix:
>     - gp1_ for Personal Access Tokens
>   ...
>
>   The overall length of our tokens will remain the same for now. However, GitHub tokens will likely increase in length in future updates, so integrators should plan to support tokens up to 255 characters after June 1, 2021.

This needs to change:

https://github.com/r-lib/gh/blob/978cb6e7e934a384aac2c63a090cc0b9ffb6e057/R/gh_token.R#L75-L83

**Comment by pat-s** [comment]
It seems like starting today many of or [CI builds](https://github.com/mlr-org/mlr3cluster/runs/2242888679?check_suite_focus=true#step:14:1175) got bit by this.

Is this likely to be solved in {gh} soon or should we manually update all of our tokens?
