### ISSUE TITLE
How to get names of private repositories?

### ISSUE THREAD

**Issue by RobinKohrs** [r-lib/gh#164]
Even if I set my PAT with `gitcreds::gitcreds_set`, I can only find my publically available repositories at the endpoint `/users/{username}/repos`. However, at the endpoint `/repos/{username}/{repo}` I can find all the information about specific private repos. So is there any way to get a list of the private repos (or all repos, the public and private ones).

I think this is a misunderstanding on my side. But maybe someone got any idea:)

**Comment by gaborcsardi** [comment]
See the docs: https://docs.github.com/en/rest/reference/repos

Use `/user/repos` for the user that belongs to the PAT, together with `visibility = "private"` if you want.

Use `/orgs/{org}/repos` for private repos in an organization. 

IDK if there is a way to list the private repos of a single another user, without using the GraphQL API.

**Comment by RobinKohrs** [comment]
Thank you very much!! So if I have a PAT saved, automatically the information for the owner of this PAT is queried?

**Comment by gaborcsardi** [comment]
Seems like it.
