### ISSUE TITLE
Allow for lower-case method?

### ISSUE THREAD

**Issue by maelle** [r-lib/gh#166]
When copying from the API docs (in Firefox, not sure if relevant) I get e.g. `get /users/{username}/repos` so I can't just paste it into my code.

Not a major inconvenience for sure, but I was wondering whether the method could be transformed directly into upper-case?

**Comment by gaborcsardi** [comment]
Interesting. So in Firefox if you copy from here: https://docs.github.com/en/rest/reference/repos#list-organization-repositories you get a lowercase `get`? 

Sure, we can allow lowercase as well, do you want to submit a PR?

**Comment by maelle** [comment]
Yes that's exactly what happens. :sweat_smile: 

I'll make a PR but in 1.5-2 weeks. :slightly_smiling_face:

**Comment by gaborcsardi** [comment]
> Yes that's exactly what happens. 😅

wow

> I'll make a PR but in 1.5-2 weeks. 🙂

👍

**Comment by maelle** [comment]
In my case the "get" is lower-case, turned into upper-case by CSS.
