### ISSUE TITLE
Undeclared dependency on rlang results in CI errors

### ISSUE THREAD

**Issue by jeroen** [r-lib/gh#170]
A lot of my CI in which I use `gh` is failing with messages

```
<packageNotFoundError in loadNamespace(x): there is no package called ‘rlang’>
```

To reproduce locally:

```r
> remove.packages('rlang')
Removing package from ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library’

## Restart R
> gh::gh("/repos/r-lib/test")
Error in loadNamespace(x) : there is no package called ‘rlang’
```

I think the problem is that rlang is used here, but not declared as a dependency:

https://github.com/r-lib/gh/blob/61a9a47c2879b921cddb2477f4af355fef59dad8/R/gh_response.R#L42

**Comment by gaborcsardi** [comment]
Fixed by cd83ba94ac92a56d69df0fd1bb51c284c29e9505
