### ISSUE TITLE
Are higher-level GraphQL functions in scope of this package?

### ISSUE THREAD

**Issue by salim-b** [r-lib/gh#173]
Some time ago I've written three (two of them non-trivial) functions based on `gh::gh_gql()`:

- [`gh_dir_ls`](https://rpkg.dev/pal/reference/gh_dir_ls.html)
- [`gh_text_file()`](https://rpkg.dev/pal/reference/gh_text_file.html)
- [`gh_text_files()`](https://rpkg.dev/pal/reference/gh_text_files.html) (convenience wrapper combining the first two functions)

Currently they live in my [pal](https://rpkg.dev/pal/) package. It's not on CRAN, the development version can be installed via `remotes::install_gitlab("salim_b/r/pkgs/pal")`. Sources are found [here](https://gitlab.com/salim_b/r/pkgs/pal/-/blob/master/Rmd/pal.Rmd#github).

In [this comment](https://github.com/r-lib/gh/issues/131#issuecomment-724161018) I sense reservations against the introduction of higher-level functions in gh. Still, I think those functions could be useful for a broader audience, so I'd like to ask whether you're open for a pull request to directly include them in gh.

**Comment by gaborcsardi** [comment]
Thanks! Those functions are indeed out of scope here. No doubt that they are useful, but we want to keep gh minimal and un-opinionated.

We could potentially include them in the documentation as examples, but even that has a non-trivial amount of maintenance burden.

**Comment by salim-b** [comment]
Ok, understood. It was worth a try. 😄
