### ISSUE TITLE
code search endpoint not working with gh, but working with httr::GET

### ISSUE THREAD

**Issue by FMKerckhof** [r-lib/gh#182]
Dear, I am trying to use the [REST API search/code endpoint](https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-code) with `gh::gh` but I keep on getting no hits. Nevertheless, if I use `httr::GET` to query the same endpoint results are found  - am I missing certain configuration parameters of the `gh` function or are these endpoints simply not (yet) supported?

Full reprex below, minus GitHub PAT .

``` r
library(reprex)
library(gh)

gh("GET /search/code?q=installation+repo:r-lib/gh",
   .token=Sys.getenv("GH_PAT"),
   .send_headers = c(`X-GitHub-Api-Version`="2022-11-28"))
#> {
#>   "total_count": 0,
#>   "incomplete_results": false,
#>   "items": []
#> }

httr::GET('https://api.github.com/search/code?q=installation+repo:r-lib/gh',
          httr::add_headers('X-GitHub-Api-Version'="2022-11-28",
                            Authorization=paste0("Bearer ",Sys.getenv("GH_PAT"))))
#> Response [https://api.github.com/search/code?q=installation+repo:r-lib/gh]
#>   Date: 2023-07-18 14:13
#>   Status: 200
#>   Content-Type: application/json; charset=utf-8
#>   Size: 14.9 kB
#> {
#>   "total_count": 3,
#>   "incomplete_results": false,
#>   "items": [
#>     {
#>       "name": "README.Rmd",
#>       "path": "README.Rmd",
#>       "sha": "8f332ead268d40989b6a27601330942809c5b671",
#>       "url": "https://api.github.com/repositories/37042992/contents/README.Rm...
#>       "git_url": "https://api.github.com/repositories/37042992/git/blobs/8f33...
#> ...
```

<sup>Created on 2023-07-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
Let gh process the query for you:

``` r
x <- gh::gh(
  "/search/code",
  q = "installation repo:r-lib/gh",
  .token=Sys.getenv("GH_PAT"),
  .send_headers = c("X-GitHub-Api-Version" = "2022-11-28")
)
str(x, list.len = 3, give.attr = FALSE)
#> List of 3
#>  $ total_count       : int 3
#>  $ incomplete_results: logi FALSE
#>  $ items             :List of 3
#>   ..$ :List of 8
#>   .. ..$ name      : chr "README.Rmd"
#>   .. ..$ path      : chr "README.Rmd"
#>   .. ..$ sha       : chr "8f332ead268d40989b6a27601330942809c5b671"
#>   .. .. [list output truncated]
#>   ..$ :List of 8
#>   .. ..$ name      : chr "README.md"
#>   .. ..$ path      : chr "README.md"
#>   .. ..$ sha       : chr "81e7be9182934d2ae6b734d78c7707e2eafdf21d"
#>   .. .. [list output truncated]
#>   ..$ :List of 8
#>   .. ..$ name      : chr "managing-personal-access-tokens.Rmd"
#>   .. ..$ path      : chr "vignettes/managing-personal-access-tokens.Rmd"
#>   .. ..$ sha       : chr "34853afae36a9df0d009af2647874cd827db26f0"
#>   .. .. [list output truncated]
```

**Comment by FMKerckhof** [comment]
@jennybc : thank you for helping me get unstuck. In order to understand why it works, I took a deeper look at `?gh::gh` and indeed it states that the `...` parameter should be given as key-value pairs which will be sent as query parameters in GET requests. 

> Name-value pairs giving API parameters. Will be matched into endpoint placeholders, sent as query parameters in GET requests, and as a JSON body of POST requests. If there is only one unnamed parameter, and it is a raw vector, then it will not be JSON encoded, but sent as raw data, as is. This can be used for example to add assets to releases. Named NULL values are silently dropped. For GET requests, named NA values trigger an error. For other methods, named NA values are included in the body of the request, as JSON null.

On why it doesn't work with the full endpoint as specified in the GitHub REST API docs I would assume that, as @gaborcsardi suggests, this has something to do with URI encoding. Nevertheless, I think it would be nice to have an example in the examples section of the gh::gh man page. Are you open for contributions? I'm willing to add the above example myself to help people like me (who typically scroll straight to the examples section to understand how functions work) who'd otherwise get stuck 😃

**Comment by jennybc** [comment]
2020 @gaborcsardi knew about the spaces 😏 

https://github.com/r-lib/gh/issues/82#issuecomment-576699060

**Comment by gaborcsardi** [comment]
@FMKerckhof Sure, a PR with an example would be great! Thanks!

**Comment by FMKerckhof** [comment]
done: https://github.com/r-lib/gh/pull/183
