### ISSUE TITLE
Recommend gitcreds more?

### ISSUE THREAD

**Issue by maelle** [r-lib/gh#194]
I was reading the docs/code to find where the fallback on the `GITHUB_TOKEN` environment variable happens (in gitcreds :sweat_smile:) and noticed that while gitcreds docs state

```r
#' However, we still suggest that you add your token to the git credential
#' store with `gitcreds_set()` and remove `GITHUB_PAT` from your
#' `.Renviron` file. The credential store is more secure than storing
#' tokens in files, and command line git also uses the credential store
#' for password-less authentication.
```

here in gh,

- the README doesn't mention gitcreds at all.
- the docs of the param .token are

https://github.com/r-lib/gh/blob/1ac24e436647c608b145e848ea994fe99c8ffe8f/R/gh.R#L43-L46

- the example mention the environment variables https://github.com/r-lib/gh/blob/1ac24e436647c608b145e848ea994fe99c8ffe8f/R/gh.R#L94

**Comment by gaborcsardi** [comment]
Well, a PR is welcome. 😉
