### ISSUE TITLE
What to do with NA input to `gh()`?

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#21]
If `...` in `gh(endpoint, ...)` contains an NA, `gh()` errors with this:

```
 Error in if (endpoint2 != endpoint) { : 
  missing value where TRUE/FALSE needed 
```

Obviously you'd never do that intentionally. I'm using `gh()` over rather long lists of (alleged) GitHub users, repos, teams, etc. and sometimes this just happens. I wonder if there's a nicer way to handle?

I'm working on another PR re: errors and will also try to propose something for this.

**Comment by gaborcsardi** [comment]
That page has some good links. E.g. this looks good:
https://github.com/apiaryio/api-blueprint/

And there a lot of others, e.g. here: https://news.ycombinator.com/item?id=8912897

It is not easy to search for a GitHub api spec, because all these tools are actually **on** GitHub. 

You know what, I'll just ask GitHub support....

**Comment by gaborcsardi** [comment]
Question sent. 

Btw., you said the Python client has this already? Let me take a look.

**Comment by gaborcsardi** [comment]
Well, they have it in "Python code", so that is not really ideal....

**Comment by gaborcsardi** [comment]
GH support replied, they don't have a machine-readable api spec, but they want to create one. No ETA, though.

**Comment by gaborcsardi** [comment]
I mentioned this already for another issue, but there is a good list of endpoints here: https://github.com/mikedeboer/node-github/blob/master/lib/routes.json

**Comment by gaborcsardi** [comment]
To return back to the original issue, I think NAs should generate errors, no? What else could we do in this case?

**Comment by jennybc** [comment]
I agree.

I now call `gh()` almost exclusively in a `purrr::safely(gh)()` form. To cope with all manner of errors.

In fact, I wonder if if makes sense to build anything like that into `gh()`?

**Comment by gaborcsardi** [comment]
I don't think I would run in `safely` be default. Users can do that if they want, I would just return *good* errors, i.e. using https://github.com/ropenscilabs/fauxpas or https://github.com/sckott/httpcode.

**Comment by jennybc** [comment]
No, not by default.

I should clarify that I'm usually using `safe_gh()` inside `purrr::map2()` or `purrr::pmap()`. So I am noticing a very standard set of gymnastic moves that I do before (creating `safe_gh()`) and after (looking at the errors and, God willing, extracting the "good results").
