### ISSUE TITLE
Unable to use `gh::gh()` with public repositories on GitHub if SAML turned on (GitHub Enterprise) if a PAT has been created

### ISSUE THREAD

**Issue by e-perl-NOAA** [r-lib/gh#216]
## Background
We have public repositories on GitHub Enterprise. SAML is turned on. But the repos are fully public and there are no restrictions to downloading, cloning, or forking. But if we try to use gh::gh() with those repositories, we get an error if the user has a PAT. Deleting the PAT will cause the installation to work, however, there may be instances where people do not want to delete the PAT because they are using it for other things. The error is only with public repos on GitHub Enterprise with SAML turned on. See [a similar issue with the `remotes` package](https://github.com/r-lib/remotes/issues/818) that other people in our GitHub Enterprise just posted.

## How to Reproduce
** this was reproduced using posit cloud***

1. Make sure a PAT is created.
```
usethis::create_github_token() 
credentials::set_github_pat("YourPAT")
```
2. Try to use {gh} to get the latest release from a repository on GitHub Enterprise where SAML is turned on. The following error appears:
```
gh::gh("GET /repos/nmfs-ost/ss3-source-code/releases/latest", page = 1)
Error in `gh::gh()`:
! GitHub API error (403): Resource protected by
  organization SAML enforcement. You must grant your Personal
  Access token access to this organization.
ℹ Read more at
  <https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/>
Run `rlang::last_trace()` to see where the error occurred.
```

* adding the .token = NULL parameter created the same error

3. Delete the PAT
```
usethis::edit_r_environ()
gitcreds::gitcreds_delete()
```
4.  Restart R and try gh again
```
gh::gh("GET /repos/nmfs-ost/ss3-source-code/releases/latest", page = 1)
```

## Possible solution

Create a parameter that tells the function to not look for a token, such as `dont_use_token = TRUE` that would not use gh_token().

By commenting out lines, adding the modified lines in the package, and trying the reloaded gh package with my modifications using a PAT again resolved the issue for me. Of course you wouldn't want to do exactly as I did because in many situations you want the token, but having an option to use my replacement with something like what I suggested above would be helpful.

In gh_request.R
```
# auth <- gh_auth(x$token %||% gh_token(x$api_url))
auth <- gh_auth(x$token)
```

In gh_rate_limit.R and in gh_whoami.R
```
# .token <- .token %||% gh_token(.api_url)
 .token <- .token
```

**Comment by gaborcsardi** [comment]
Try this, then gh should not send a token: 
```
gh::gh(..., .token = NA_character_)
```

**Comment by e-perl-NOAA** [comment]
That works! Thank you so much!
