### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#26]
Is it feasible for `gh` to indicate progress?

**Comment by gaborcsardi** [comment]
When making multiple rounds of queries? I guess a single query is always fast.

**Comment by jennybc** [comment]
I'm making some queries now that retrieve thousands of items and take several minutes. It would be comforting to have some sense of progress.

I guess I actually know from using the API directly how easy (or, annoying, rather) it is to learn the total number of items available.

What do you think of showing progress, perhaps only when `.limit = Inf`?

**Comment by gaborcsardi** [comment]
Yeah, whenever `.limit` is bigger than 30 we can do it I guess. For the `.limit = Inf` case when there is a `rel="last"` link we can do a proper progress bar, without that we can only do a counter that shows how many queries have completed.

**Comment by gaborcsardi** [comment]
I am rewriting https://github.com/gaborcsardi/progress, again. And it will be awesome, of course. Once that is done, I'll get to this.
