### ISSUE TITLE
Explore getting credentials from the OS keychain

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gh#30]
Idea from #29

**Comment by gaborcsardi** [comment]
Here is a good looking cross platform app in pure python: https://github.com/jaraco/keyring
Far from trivial, so I'll close this for now.

**Comment by gaborcsardi** [comment]
And here is one in C++ / coffeescript for node: https://github.com/atom/node-keytar

Maybe we could use this directly, actually.

**Comment by gaborcsardi** [comment]
@hadley started a simple keyring package: https://github.com/MangoTheCat/keyring

Generic passwords on OSX already work! Other platforms not tested, and internet passwords don't work yet.

**Comment by jennybc** [comment]
This is something rOpenSci has discussed working on also, so paging @karthik.

**Comment by gaborcsardi** [comment]
@jennybc @karthik Oh, cool!

**Comment by gaborcsardi** [comment]
I worked a bit on https://github.com/MangoTheCat/keyring, and 
* on macOS it supports 'generic' and 'internet' passwords, which is all we need. It is easy to get out your github.com username and password for example, automatically.
* on Windows everything is messed up: 
    - browsers do not store the passwords in the OS keychain (by default). 
    - recent IE versions store them in "Web credentials", and I didn't find a good API for this. There must be one, I think. https://github.com/MangoTheCat/keyring/issues/4
    - Older IE versions use the registry, and I don't think I want to support them.
    - Chrome stores password in its own settings. It is possible to get them out, but quite hacky.
    - Firefox also uses its own storage.
    - All browsers can be set up to actually use the system keyring (vault), but I don't that this is common, except maybe for companies that manage this setting, and only for passwords for some dedicated websites.
* Linux is yet to be tested https://github.com/MangoTheCat/keyring/issues/5
