### ISSUE TITLE
search api results concatenation is wrong

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gh#33]
We need to concatenate `$items`, not the answer itself.

**Comment by jennybc** [comment]
For the same underlying reason, `.limit` has no effect when hitting the search endpoint 😔.

**Comment by gaborcsardi** [comment]
I think this would need a special `gh_search()` function, to be able to handle things differently.

**Comment by krlmlr** [comment]
This is for e.g. `gh("/search/code")` . I'm taking this.

**Comment by gaborcsardi** [comment]
I think with the recent changes this actually works well:
```r
ret <- gh("/search/code", q = "sapply org:cran", .limit=30, per_page=10)
```

We could still have a `gh_search()` function, but concatenation works now.
