### ISSUE TITLE
List your gh package on github's official list of API libraries

### ISSUE THREAD

**Issue by daattali** [r-lib/gh#34]
There is currently no library for R on the page

https://developer.github.com/libraries/

**Comment by gaborcsardi** [comment]
Good idea! TBH I am not 100% comfortable yet putting it there. It should have test cases at least. But I'll think about it and keep this issue open.

**Comment by gaborcsardi** [comment]
OK, #8 (test cases) is improving, so we'll get there soon, hopefully!

**Comment by krlmlr** [comment]
It's on CRAN now, I love the design. Maybe it's time to list it? ;-)

**Comment by gaborcsardi** [comment]
OK, now I just need to find out what to do....

**Comment by gaborcsardi** [comment]
Sent a support request...

**Comment by gaborcsardi** [comment]
So, apparently they did not add it.

**Comment by daattali** [comment]
What's the reasoning?

**Comment by gaborcsardi** [comment]
It just never happened: 

<img width="883" alt="Screen Shot 2020-01-21 at 16 41 33" src="https://user-images.githubusercontent.com/660288/72824277-e7b8bd80-3c6c-11ea-82c3-ad6e294184f5.png">

**Comment by daattali** [comment]
That's dumb. I'm going to email them too.
