### ISSUE TITLE
downloading binary file associated with a release (an "asset")

### ISSUE THREAD

**Issue by aammd** [r-lib/gh#57]
It seems that `gh` is able to successfully read the JSON information about a release -- including information about any assets which are attached to it -- but it cannot download the binary file (examples based on [this public repository](https://github.com/aammd/test_idea/releases):

```r
# this works fine
gh::gh("https://api.github.com/repos/aammd/test_idea/releases/assets/2998763")
gh::gh("/repos/:owner/:repo/releases/assets/:id", owner = "aammd", repo = "test_idea", id = "2998763")

# this does not
gh::gh("https://api.github.com/repos/aammd/test_idea/releases/assets/2998763", .send_headers = c("Accept" = "application/octet-stream"))
gh::gh("/repos/:owner/:repo/releases/assets/:id", owner = "aammd", repo = "test_idea", id = "2998763", .send_headers = c("Accept" = "application/octet-stream"))

#No encoding supplied: defaulting to UTF-8.
#No encoding supplied: defaulting to UTF-8.
#Error in gh::gh("/repos/:owner/:repo/releases/assets/:id", owner = "aammd",  : 
#  GitHub API error (400): 
#  <?xml version="1.0" encoding="UTF-8"?>
#<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the #X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header #should be specified...
```
The above was from a session where I have my `GITHUB_TOKEN` set. In this case, the problem is caused by authentification information being communicated twice: once in a header and once in the URL itself. This happens even though the repo is public (and authentification is not necessary)

If I remove my `GITHUB_TOKEN`,  a different problem appears:
```r
Sys.setenv(GITHUB_TOKEN = "")
gh::gh("https://api.github.com/repos/aammd/test_idea/releases/assets/2998763", .send_headers = c("Accept" = "application/octet-stream"))
#No encoding supplied: defaulting to UTF-8.
#{
# "message": "X\n"
#} 
```

However, `httr::GET()` works just fine: 

```r
httr::GET("https://api.github.com/repos/aammd/test_idea/releases/assets/2998763", 
          .send_headers = c("Accept" = "application/octet-stream"),
          httr::write_disk("test.rds", overwrite = TRUE))
```

I'm not sure where the fix ought to be made -- perhaps in `gh_make_request`?

### same problem with private repos

We get a similar problem with private repos, except that in this case of course authentification _is_ necessary. I don't want to make this issue overlong, so there are two possible solutions on [this Stackoverflow question i asked](http://stackoverflow.com/questions/41696199/authentication-to-github-private-repositories-with-httr/41709121#41709121).

**Comment by maelle** [comment]
:wave: @aammd you might like this new package of @cboettig's https://github.com/cboettig/piggyback that has "a simple interface for directly uploading and downloading individual data files to a GitHub release."

**Comment by cderv** [comment]
I have the same issue trying to use the Archive link API
https://developer.github.com/v3/repos/contents/#get-archive-link

I think this is because the response if parsed as text and not as it should be (in my case `application/x-gzip`). it passes all the text in the code below and is then parsed as text, which is wrong.

https://github.com/r-lib/gh/blob/bed43d354789d2e4dde75db0327da1d46358f953/R/gh_response.R#L1-L24

All the returned content are not dealt with. This should be seen with the correct content is `as = "text"` was not forced. 

Should `gh` handles all the response type from github API ?

**Comment by ha0ye** [comment]
This seems like it might be resolved in #77?

**Comment by gaborcsardi** [comment]
For the double-authentication after redirect problem, you can do this in gh:

```r
gh::gh(
  "https://api.github.com/repos/aammd/test_idea/releases/assets/2998763",
  access_token = gh_token(),
  .send_headers = c("Accept" = "application/octet-stream"),
  .token = NA)
```

This forces the token to be a query parameter, and removes it from the HTTP header.

I believe that parsing of the `application/octet-stream` response is fixed.

**Comment by cboettig** [comment]
> This forces the token to be a query parameter, and removes it from the HTTP header.

@gaborcsardi Is your comment above still accurate?   In #106 you suggest that `gh` never sends tokens in the query parameter (which GitHub has now deprecated, as documented in #106).    I confess I'm at a bit of a loss as to how we handle this 'download asset' case in light of the deprecation...

**Comment by cboettig** [comment]
From #97 I see there's now `.destfile`, but I'm not having any luck:

```r
gh("https://api.github.com/repos/cboettig/piggyback-tests/releases/assets/8990141", 
 .destfile = "test.tsv.gz", .send_headers = c("Accept" = "application/octet-stream"))
```

Throws a 400 error.  (`gh` doesn't seem to show the error message, but a file called `test.tsv.gz` is actually created though it appears to be an XML file with the error message that "only one authentication mechanism is allowed; so perhaps there is also an unrelated issue in error handling with this header).  

I've tried the above with a `.token` as well with the same results...

**Comment by ha0ye** [comment]
@cboettig Falling back to using `httr::GET`, I get the same error with
```r
httr::GET("https://api.github.com/repos/cboettig/piggyback-tests/releases/assets/8990141", 
          c(httr::authenticate(gh_token(), "x-oauth-basic", "basic"), 
            httr::write_disk("test.tsv.gz", overwrite = TRUE), 
            httr::accept("application/octet-stream")))
```

but dropping the authentication from the header config made it work:
```r
httr::GET("https://api.github.com/repos/cboettig/piggyback-tests/releases/assets/8990141", 
          c(httr::write_disk("test.tsv.gz", overwrite = TRUE), 
            httr::accept("application/octet-stream")))
```

I don't know how to enable this in `gh`, since it defaults to `gh_token`. If I try `Sys.unsetenv("GITHUB_PAT")` before running your example `gh()` call, it works, but this seems like a bad workaround.

**Comment by cboettig** [comment]
Thanks @ha0ye!  right, like you say we want to be able to authenticate so we can download assets from private repositories as well (though obviously that doesn't work so well for reprexs).  Is this just my repo? Can you download assets from private repos?

I can get this to work with the auth in a query parameter, but these days that leads to the deprecation notification in #106....
