### ISSUE TITLE
better error messages

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gh#60]
https://github.com/jimhester/lookup/issues/15#issuecomment-305891267

**Comment by jennybc** [comment]
Here's a good example to check when someone works on this: try to create a repo that already exists. Current feedback is just `422 Unprocessable Entity` but I suspect/hope there's a better message that can be exposed.

**Comment by hadley** [comment]
Would also be nice to print the generated url to help in situations like

```
 Error in gh::gh("GET /repos/:owner/:repo", owner = pieces[1], repo = pieces[2]) : 
  GitHub API error (404): 404 Not Found
  Not Found 
```

**Comment by jennybc** [comment]
Another good test case: exposing the message when you get 403 after exceeding rate limit

https://developer.github.com/v3/#rate-limiting

<img width="665" alt="screen shot 2018-01-22 at 11 20 07 am" src="https://user-images.githubusercontent.com/599454/35239912-ae9d6dec-ff66-11e7-9b9d-58a67d098c9c.png">
