### ISSUE TITLE
CRAN release timing?

### ISSUE THREAD

**Issue by cboettig** [r-lib/gh#61]
Any plans to put `gh` on CRAN in the near future?  It's a great package and particularly handy for creating nice examples with json data in other packages, among other uses.  Thanks!

**Comment by gaborcsardi** [comment]
Thanks for the heads up! Just submitted it.

**Comment by gaborcsardi** [comment]
It took some time and effort, but it is on CRAN now. :)

**Comment by cboettig** [comment]
Thanks! :rocket:
