### ISSUE TITLE
Use purrr in README example(s)

### ISSUE THREAD

**Issue by batpigandme** [r-lib/gh#68]
e.g. for https://github.com/r-lib/gh/blob/master/README.Rmd#L53-L54
```r
j_repos <- gh("/users/:username/repos", username = "jeroenooms")
vapply(j_repos, "[[", "", "name")
```
add example with (or swap in)
```r
j_repos %>% purrr::map_chr("name")
```
aside: I can also change to Jeroen's new GH handle (jeroen), or use a completely different example, if so desired.

**Comment by gaborcsardi** [comment]
PRs are welcome. :)

**Comment by batpigandme** [comment]
Just pitching it in an issue first, gotta take my own advice.

**Comment by jennybc** [comment]
I gather that @gaborcsardi and/or r-lib is more careful re: tidyverse-neutrality. So I'd add the purrr example *alongside* the base version. I note that gh does not even Suggest purrr at this point, so using it in README.Rmd isn't exactly a no-brainer. But I guess it should work.

**Comment by batpigandme** [comment]
@jennybc good point(s)- in that case, it might just distract.
