### ISSUE TITLE
SSO - can gh work with Single Sign On

### ISSUE THREAD

**Issue by xhudik** [r-lib/gh#70]
Hi I'm wondering whether *gh* lib can work with *SSO* (Single Sign On). 

SSO is used by many companies. I'm not a big fan of this methodology but it is relatively widely spread. If gh can use SSO - would be great if you can provide some example (i tried google but nut much joy)

thank you!

**Comment by gaborcsardi** [comment]
gh supports personal api access tokens: https://github.com/blog/1509-personal-api-tokens

I realize that they solve a lightly different problem, but it might be worth a look.

**Comment by xhudik** [comment]
thank you!
