### ISSUE TITLE
Export gh_token()

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#74]
Packages such as usethis delegate GitHub API work to gh.

But sometimes the logic in the other package needs to know whether gh is going to be able to find a token.

@gaborcsardi Is it ok if I export `gh_token()`?

**Comment by gaborcsardi** [comment]
I don't mind exporting it if you need it. But what do you actually need? Just the fact that there is a token, or that there is a valid token? A valid token with certain permissions?

**Comment by jennybc** [comment]
`usethis::create_from_github()` creates a new local repo & project from a GitHub repo.

One could either clone or fork & clone. Yes, there is a logical `fork` argument. But I want nice default behaviour: if no PAT is explicitly provided and no preconfigured PAT is available, it's clear we must default to `fork = FALSE`.

So far, I've just copied `gh_token()` over into usethis:

``` r
gh_token <- function() {
  token <- Sys.getenv('GITHUB_PAT', "")
  if (token == "") Sys.getenv("GITHUB_TOKEN", "") else token
}

## blah blah
pat <- auth_token %||% gh_token()
pat_available <- pat != ""
```

but it would be better if gh just told me whether it thinks it can find a PAT.

Maybe what I really want is this:

```
token_available <- function() !identical(gh_token(), "")
```

**Comment by gaborcsardi** [comment]
TBH, this seems a bit magical to me, and it makes `create_from_github()` harder to use programmatically: you always need an explicit `fork` argument, otherwise the behavior depends on external context.

OTOH, I understand that this is mainly for interactive use, and then it makes sense. 

Anyway, I don't mind exporting `gh_token()`.

**Comment by jennybc** [comment]
Yeah, this is for interactive use.

The default behaviour of `fork` predates me, but I can raise this question when I get Hadley to review this PR.
