### ISSUE TITLE
Sending results directly to disk

### ISSUE THREAD

**Issue by noamross** [r-lib/gh#76]
It would be nice to be able to send the contents of a response directly to disk, either as JSON or raw, without converting.  Would you take a PR to to so?  It would

-  Add a `destfile=NULL` argument to `gh()` that takes a path. Also an `overwrite=TRUE` argument to determine whether to overwrite files.
-  Pass `write_disk()` to the httr call if a path or connection is specified, bypassing the regular conversion.
-  Returns the path/connection with the standard gh attributes and class `c('gh_request', 'chr')`

**Comment by noamross** [comment]
I was on a roll: #77

**Comment by gaborcsardi** [comment]
Closed by #77.
