### ISSUE TITLE
Handle missingness

### ISSUE THREAD

**Issue by coatless** [r-lib/gh#84]
Consider the use of `NA` and `NULL` being passed into a named parameter:

```r
gh("/repos/:owner/:repo/issues", owner = "r-lib", repo = "gh", state = NULL)
# Error in gsub(paste0(":", n, "\\b"), p, endpoint) : 
#  invalid 'replacement' argument

gh("/repos/:owner/:repo/issues", owner = "r-lib", repo = "gh", state = NA)
# Error in gh("/repos/:owner/:repo/issues", owner = "r-lib", repo = "gh",  : 
#  GitHub API error (422): 422 Unprocessable Entity
#  Validation Failed
```

This is a bit problematic for parameters that may be _optional_. (c.f. https://github.com/coatless/ghapi3/issues/3)

Would it be possible to add filtering inside of `gh_set_endpoint()` in [`R/gh_request.R`](https://github.com/r-lib/gh/blob/a8b645364f59a5d5030ccfd8d074de640d8b72cd/R/gh_request.R#L49) to remove parameters that have _R_-specific missingness? e.g.

```r
gh_set_endpoint <- function(x) {
  params <- x$params
  if (!grepl(":", x$endpoint) || length(params) == 0L || has_no_names(params)) {
    return(x)
  }

  # Subset out invalid params
  params <- Filter(Negate(is.null), params)
  params <- Filter(Negate(is.na), params)

  # rest of the logic ... 
}
```

**Comment by jennybc** [comment]
Related to #21

**Comment by coatless** [comment]
Reading https://github.com/r-lib/gh/issues/21#issuecomment-260951901, it seems like the goal should be to trigger an error in the endpoint instead of silently removing the missingness components as-is described above. So, the following should be added:

```r
param_names = names(params)
missingness_params = param_names[sapply(params, function(x) is.null(x) || is.na(x)] 

if(length(missingness_params) > 0) {
   msg = paste("Parameters must not have `NA` or `NULL` as their values.",
                         "The following parameters were detected to have some level of missingness: \n"
                     paste0(missingness_params, collapse = "\n"))
   stop(msg, call. = FALSE)
}
```

Though, that leaves the case brought up in https://github.com/coatless/ghapi3/issues/3 that requires flexibility of defined parameters missing parameters for optional values. I suppose the best way to handle this is to retrieve only valid parameters prior to the `gh()` call. Thus, any named element with missingness is deleted using a custom cleaning function. The new list of parameters would then be passed to`gh()` via `do.call()`?

```r
valid_params = function(...) {
  params = list(...)
  params = Filter(Negate(is.null), params)
  params = Filter(Negate(is.na), params)
  
  params
}

repo_transfer = function(owner, repo, new_owner, team_id = NA) {

  params = valid_params(endpoint = "custom endpoint here", owner = owner, repo = repo, new_owner = new_owner, team_id = team_id)
  
  params
  
  ## Call the gh function dynamically with the subset of parameters potentially
  # do.call(gh, params)
  
}
```

**Comment by lwjohnst86** [comment]
I bypassed that [here](https://github.com/lwjohnst86/githubr/blob/master/R/utils.R) using a combination of:

```
add_request_parameters <- function(...) {
    params <- list(...)
    Filter(Negate(is.null), params)
}
```

Each param's default is NULL. Then it is passed to:

```
do.call(gh::gh, params)
```

**Comment by gaborcsardi** [comment]
I am planning to fix this by 

1. dropping _named_ `NULL` parameters silently, so `NULL` means "do add this query parameter", and 
2. throwing an error on _named_ `NA` parameters.

Non-named parameters are not touched, since they go into the request body, they will be JSON encoded, and `NA` and `NULL` are valid here. (Weird, but valid.)

**Comment by coatless** [comment]
@gaborcsardi awesome. Do you have an ETA on when the next version of `gh` will go onto CRAN?

**Comment by gaborcsardi** [comment]
today
