### ISSUE TITLE
Document GITHUB_API_URL env var for changing default one

### ISSUE THREAD

**Issue by cderv** [r-lib/gh#95]
Following r-lib/usethis#834, it seems that this feature implement in #20  is not documented. (and now lives [here](https://github.com/r-lib/gh/blob/bed43d354789d2e4dde75db0327da1d46358f953/R/gh_request.R#L108))

I think a sentence about this env var could be added in every function that uses `.api_url`. 

Even something in the readme could be useful. I guess it depends if you plan a pkgdown site for this r-lib tool. Maybe documentation on how to configure a different default GH url should live in usethis. 

I am in the train right now but happy to PR doc improvement anytime.

**Comment by gaborcsardi** [comment]
Right. Thanks much for the offer! How about having an "Environment variables" section in the `README` for a start? Like for remotes: https://github.com/r-lib/remotes#environment-variables

**Comment by cderv** [comment]
Oh I did not know that one for remote. Let's go with that!
