### ISSUE TITLE
[release request] Bump version to 1.0.2 and push to CRAN

### ISSUE THREAD

**Issue by ha0ye** [r-lib/gh#97]
Over in https://github.com/weecology/portalr, we use the `.destfile` feature to download zipped releases from GitHub. Having this feature in the package on CRAN would enable us to update our package on CRAN, too.

Thanks for the useful package and taking a look!

**Comment by cboettig** [comment]
(just a note that it looks like gh v1.1.0 is on CRAN as of 2020-01-24 https://cran.r-project.org/web/packages/gh/index.html, ping @ @ha0ye).  

Now time for me to learn more about this `.destfile` you speak of.... , e.g. #57 .  thanks for the portalr example!

**Comment by ha0ye** [comment]
Ah, thanks @cboettig! (closing the issue)
