### ISSUE TITLE
Make it easier to put gh in a tibble

### ISSUE THREAD

**Issue by hadley** [r-lib/gh#99]
``` r
library(gh)
json <- gh("GET /orgs/:org/repos", org = "tidyverse", .limit = Inf)

tibble(json = json)
#> Error: All columns in a tibble must be vectors:
#> * Column `json` is gh_response
```

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
@hadley You just want to put the list in a column? That's quite easy, just drop the class and the attributes:

``` r
library(gh)
library(tibble)

json <- gh("GET /orgs/:org/repos", org = "tidyverse", .limit = Inf)

tibble(json = c(json))
#> # A tibble: 34 x 1
#>    json             
#>    <list>           
#>  1 <named list [74]>
#>  2 <named list [74]>
#>  3 <named list [74]>
#>  4 <named list [74]>
#>  5 <named list [74]>
#>  6 <named list [74]>
#>  7 <named list [74]>
#>  8 <named list [74]>
#>  9 <named list [74]>
#> 10 <named list [74]>
#> # … with 24 more rows
```

<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
Of course it would be great to get back a "proper" tibble, with the right columns,  but that seems hard for gh, considering that the response can be anything... maybe we could support `fromJSON()`'s `simplifyVector` and `simplifyDataFrame` arguments?

**Comment by hadley** [comment]
You should be able to fix this by making the class `c("gh_response", "list")` (if not, it's a bug in tibble/vctrs)

(I should've mentioned that initially 😬)

**Comment by gaborcsardi** [comment]
Right. That's the class actually, well, usually, so your original example actually works for me. 

Sometimes the class is `c("gh_response", "path")`, if you wanted the results on disk, or `c("gh_response", "raw")` for a raw response. I don't know if these are very important for this issue, though.

**Comment by hadley** [comment]
Works for me now too! (probably because of changes to dev tibble/vctrs)
